/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e3) {
        reject(e3);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e3) {
        reject(e3);
      }
    };
    var step = (x3) => x3.done ? resolve(x3.value) : Promise.resolve(x3.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => CalibrePlugin
});
var import_obsidian2 = __toModule(require("obsidian"));

// src/settings.tsx
var import_obsidian = __toModule(require("obsidian"));

// node_modules/preact/dist/preact.module.js
var n;
var l;
var u;
var i;
var t;
var r;
var o;
var f;
var e = {};
var c = [];
var s = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;
function a(n2, l3) {
  for (var u3 in l3)
    n2[u3] = l3[u3];
  return n2;
}
function h(n2) {
  var l3 = n2.parentNode;
  l3 && l3.removeChild(n2);
}
function v(l3, u3, i3) {
  var t3, r3, o2, f3 = {};
  for (o2 in u3)
    o2 == "key" ? t3 = u3[o2] : o2 == "ref" ? r3 = u3[o2] : f3[o2] = u3[o2];
  if (arguments.length > 2 && (f3.children = arguments.length > 3 ? n.call(arguments, 2) : i3), typeof l3 == "function" && l3.defaultProps != null)
    for (o2 in l3.defaultProps)
      f3[o2] === void 0 && (f3[o2] = l3.defaultProps[o2]);
  return y(l3, f3, t3, r3, null);
}
function y(n2, i3, t3, r3, o2) {
  var f3 = { type: n2, props: i3, key: t3, ref: r3, __k: null, __: null, __b: 0, __e: null, __d: void 0, __c: null, __h: null, constructor: void 0, __v: o2 == null ? ++u : o2 };
  return o2 == null && l.vnode != null && l.vnode(f3), f3;
}
function d(n2) {
  return n2.children;
}
function _(n2, l3) {
  this.props = n2, this.context = l3;
}
function k(n2, l3) {
  if (l3 == null)
    return n2.__ ? k(n2.__, n2.__.__k.indexOf(n2) + 1) : null;
  for (var u3; l3 < n2.__k.length; l3++)
    if ((u3 = n2.__k[l3]) != null && u3.__e != null)
      return u3.__e;
  return typeof n2.type == "function" ? k(n2) : null;
}
function b(n2) {
  var l3, u3;
  if ((n2 = n2.__) != null && n2.__c != null) {
    for (n2.__e = n2.__c.base = null, l3 = 0; l3 < n2.__k.length; l3++)
      if ((u3 = n2.__k[l3]) != null && u3.__e != null) {
        n2.__e = n2.__c.base = u3.__e;
        break;
      }
    return b(n2);
  }
}
function m(n2) {
  (!n2.__d && (n2.__d = true) && t.push(n2) && !g.__r++ || o !== l.debounceRendering) && ((o = l.debounceRendering) || r)(g);
}
function g() {
  for (var n2; g.__r = t.length; )
    n2 = t.sort(function(n3, l3) {
      return n3.__v.__b - l3.__v.__b;
    }), t = [], n2.some(function(n3) {
      var l3, u3, i3, t3, r3, o2;
      n3.__d && (r3 = (t3 = (l3 = n3).__v).__e, (o2 = l3.__P) && (u3 = [], (i3 = a({}, t3)).__v = t3.__v + 1, j(o2, t3, i3, l3.__n, o2.ownerSVGElement !== void 0, t3.__h != null ? [r3] : null, u3, r3 == null ? k(t3) : r3, t3.__h), z(u3, t3), t3.__e != r3 && b(t3)));
    });
}
function w(n2, l3, u3, i3, t3, r3, o2, f3, s3, a3) {
  var h3, v3, p3, _3, b3, m2, g3, w3 = i3 && i3.__k || c, A4 = w3.length;
  for (u3.__k = [], h3 = 0; h3 < l3.length; h3++)
    if ((_3 = u3.__k[h3] = (_3 = l3[h3]) == null || typeof _3 == "boolean" ? null : typeof _3 == "string" || typeof _3 == "number" || typeof _3 == "bigint" ? y(null, _3, null, null, _3) : Array.isArray(_3) ? y(d, { children: _3 }, null, null, null) : _3.__b > 0 ? y(_3.type, _3.props, _3.key, null, _3.__v) : _3) != null) {
      if (_3.__ = u3, _3.__b = u3.__b + 1, (p3 = w3[h3]) === null || p3 && _3.key == p3.key && _3.type === p3.type)
        w3[h3] = void 0;
      else
        for (v3 = 0; v3 < A4; v3++) {
          if ((p3 = w3[v3]) && _3.key == p3.key && _3.type === p3.type) {
            w3[v3] = void 0;
            break;
          }
          p3 = null;
        }
      j(n2, _3, p3 = p3 || e, t3, r3, o2, f3, s3, a3), b3 = _3.__e, (v3 = _3.ref) && p3.ref != v3 && (g3 || (g3 = []), p3.ref && g3.push(p3.ref, null, _3), g3.push(v3, _3.__c || b3, _3)), b3 != null ? (m2 == null && (m2 = b3), typeof _3.type == "function" && _3.__k === p3.__k ? _3.__d = s3 = x(_3, s3, n2) : s3 = P(n2, _3, p3, w3, b3, s3), typeof u3.type == "function" && (u3.__d = s3)) : s3 && p3.__e == s3 && s3.parentNode != n2 && (s3 = k(p3));
    }
  for (u3.__e = m2, h3 = A4; h3--; )
    w3[h3] != null && (typeof u3.type == "function" && w3[h3].__e != null && w3[h3].__e == u3.__d && (u3.__d = k(i3, h3 + 1)), N(w3[h3], w3[h3]));
  if (g3)
    for (h3 = 0; h3 < g3.length; h3++)
      M(g3[h3], g3[++h3], g3[++h3]);
}
function x(n2, l3, u3) {
  for (var i3, t3 = n2.__k, r3 = 0; t3 && r3 < t3.length; r3++)
    (i3 = t3[r3]) && (i3.__ = n2, l3 = typeof i3.type == "function" ? x(i3, l3, u3) : P(u3, i3, i3, t3, i3.__e, l3));
  return l3;
}
function A(n2, l3) {
  return l3 = l3 || [], n2 == null || typeof n2 == "boolean" || (Array.isArray(n2) ? n2.some(function(n3) {
    A(n3, l3);
  }) : l3.push(n2)), l3;
}
function P(n2, l3, u3, i3, t3, r3) {
  var o2, f3, e3;
  if (l3.__d !== void 0)
    o2 = l3.__d, l3.__d = void 0;
  else if (u3 == null || t3 != r3 || t3.parentNode == null)
    n:
      if (r3 == null || r3.parentNode !== n2)
        n2.appendChild(t3), o2 = null;
      else {
        for (f3 = r3, e3 = 0; (f3 = f3.nextSibling) && e3 < i3.length; e3 += 2)
          if (f3 == t3)
            break n;
        n2.insertBefore(t3, r3), o2 = r3;
      }
  return o2 !== void 0 ? o2 : t3.nextSibling;
}
function C(n2, l3, u3, i3, t3) {
  var r3;
  for (r3 in u3)
    r3 === "children" || r3 === "key" || r3 in l3 || H(n2, r3, null, u3[r3], i3);
  for (r3 in l3)
    t3 && typeof l3[r3] != "function" || r3 === "children" || r3 === "key" || r3 === "value" || r3 === "checked" || u3[r3] === l3[r3] || H(n2, r3, l3[r3], u3[r3], i3);
}
function $(n2, l3, u3) {
  l3[0] === "-" ? n2.setProperty(l3, u3) : n2[l3] = u3 == null ? "" : typeof u3 != "number" || s.test(l3) ? u3 : u3 + "px";
}
function H(n2, l3, u3, i3, t3) {
  var r3;
  n:
    if (l3 === "style")
      if (typeof u3 == "string")
        n2.style.cssText = u3;
      else {
        if (typeof i3 == "string" && (n2.style.cssText = i3 = ""), i3)
          for (l3 in i3)
            u3 && l3 in u3 || $(n2.style, l3, "");
        if (u3)
          for (l3 in u3)
            i3 && u3[l3] === i3[l3] || $(n2.style, l3, u3[l3]);
      }
    else if (l3[0] === "o" && l3[1] === "n")
      r3 = l3 !== (l3 = l3.replace(/Capture$/, "")), l3 = l3.toLowerCase() in n2 ? l3.toLowerCase().slice(2) : l3.slice(2), n2.l || (n2.l = {}), n2.l[l3 + r3] = u3, u3 ? i3 || n2.addEventListener(l3, r3 ? T : I, r3) : n2.removeEventListener(l3, r3 ? T : I, r3);
    else if (l3 !== "dangerouslySetInnerHTML") {
      if (t3)
        l3 = l3.replace(/xlink[H:h]/, "h").replace(/sName$/, "s");
      else if (l3 !== "href" && l3 !== "list" && l3 !== "form" && l3 !== "tabIndex" && l3 !== "download" && l3 in n2)
        try {
          n2[l3] = u3 == null ? "" : u3;
          break n;
        } catch (n3) {
        }
      typeof u3 == "function" || (u3 != null && (u3 !== false || l3[0] === "a" && l3[1] === "r") ? n2.setAttribute(l3, u3) : n2.removeAttribute(l3));
    }
}
function I(n2) {
  this.l[n2.type + false](l.event ? l.event(n2) : n2);
}
function T(n2) {
  this.l[n2.type + true](l.event ? l.event(n2) : n2);
}
function j(n2, u3, i3, t3, r3, o2, f3, e3, c3) {
  var s3, h3, v3, y3, p3, k2, b3, m2, g3, x3, A4, P3 = u3.type;
  if (u3.constructor !== void 0)
    return null;
  i3.__h != null && (c3 = i3.__h, e3 = u3.__e = i3.__e, u3.__h = null, o2 = [e3]), (s3 = l.__b) && s3(u3);
  try {
    n:
      if (typeof P3 == "function") {
        if (m2 = u3.props, g3 = (s3 = P3.contextType) && t3[s3.__c], x3 = s3 ? g3 ? g3.props.value : s3.__ : t3, i3.__c ? b3 = (h3 = u3.__c = i3.__c).__ = h3.__E : ("prototype" in P3 && P3.prototype.render ? u3.__c = h3 = new P3(m2, x3) : (u3.__c = h3 = new _(m2, x3), h3.constructor = P3, h3.render = O), g3 && g3.sub(h3), h3.props = m2, h3.state || (h3.state = {}), h3.context = x3, h3.__n = t3, v3 = h3.__d = true, h3.__h = []), h3.__s == null && (h3.__s = h3.state), P3.getDerivedStateFromProps != null && (h3.__s == h3.state && (h3.__s = a({}, h3.__s)), a(h3.__s, P3.getDerivedStateFromProps(m2, h3.__s))), y3 = h3.props, p3 = h3.state, v3)
          P3.getDerivedStateFromProps == null && h3.componentWillMount != null && h3.componentWillMount(), h3.componentDidMount != null && h3.__h.push(h3.componentDidMount);
        else {
          if (P3.getDerivedStateFromProps == null && m2 !== y3 && h3.componentWillReceiveProps != null && h3.componentWillReceiveProps(m2, x3), !h3.__e && h3.shouldComponentUpdate != null && h3.shouldComponentUpdate(m2, h3.__s, x3) === false || u3.__v === i3.__v) {
            h3.props = m2, h3.state = h3.__s, u3.__v !== i3.__v && (h3.__d = false), h3.__v = u3, u3.__e = i3.__e, u3.__k = i3.__k, u3.__k.forEach(function(n3) {
              n3 && (n3.__ = u3);
            }), h3.__h.length && f3.push(h3);
            break n;
          }
          h3.componentWillUpdate != null && h3.componentWillUpdate(m2, h3.__s, x3), h3.componentDidUpdate != null && h3.__h.push(function() {
            h3.componentDidUpdate(y3, p3, k2);
          });
        }
        h3.context = x3, h3.props = m2, h3.state = h3.__s, (s3 = l.__r) && s3(u3), h3.__d = false, h3.__v = u3, h3.__P = n2, s3 = h3.render(h3.props, h3.state, h3.context), h3.state = h3.__s, h3.getChildContext != null && (t3 = a(a({}, t3), h3.getChildContext())), v3 || h3.getSnapshotBeforeUpdate == null || (k2 = h3.getSnapshotBeforeUpdate(y3, p3)), A4 = s3 != null && s3.type === d && s3.key == null ? s3.props.children : s3, w(n2, Array.isArray(A4) ? A4 : [A4], u3, i3, t3, r3, o2, f3, e3, c3), h3.base = u3.__e, u3.__h = null, h3.__h.length && f3.push(h3), b3 && (h3.__E = h3.__ = null), h3.__e = false;
      } else
        o2 == null && u3.__v === i3.__v ? (u3.__k = i3.__k, u3.__e = i3.__e) : u3.__e = L(i3.__e, u3, i3, t3, r3, o2, f3, c3);
    (s3 = l.diffed) && s3(u3);
  } catch (n3) {
    u3.__v = null, (c3 || o2 != null) && (u3.__e = e3, u3.__h = !!c3, o2[o2.indexOf(e3)] = null), l.__e(n3, u3, i3);
  }
}
function z(n2, u3) {
  l.__c && l.__c(u3, n2), n2.some(function(u4) {
    try {
      n2 = u4.__h, u4.__h = [], n2.some(function(n3) {
        n3.call(u4);
      });
    } catch (n3) {
      l.__e(n3, u4.__v);
    }
  });
}
function L(l3, u3, i3, t3, r3, o2, f3, c3) {
  var s3, a3, v3, y3 = i3.props, p3 = u3.props, d3 = u3.type, _3 = 0;
  if (d3 === "svg" && (r3 = true), o2 != null) {
    for (; _3 < o2.length; _3++)
      if ((s3 = o2[_3]) && "setAttribute" in s3 == !!d3 && (d3 ? s3.localName === d3 : s3.nodeType === 3)) {
        l3 = s3, o2[_3] = null;
        break;
      }
  }
  if (l3 == null) {
    if (d3 === null)
      return document.createTextNode(p3);
    l3 = r3 ? document.createElementNS("http://www.w3.org/2000/svg", d3) : document.createElement(d3, p3.is && p3), o2 = null, c3 = false;
  }
  if (d3 === null)
    y3 === p3 || c3 && l3.data === p3 || (l3.data = p3);
  else {
    if (o2 = o2 && n.call(l3.childNodes), a3 = (y3 = i3.props || e).dangerouslySetInnerHTML, v3 = p3.dangerouslySetInnerHTML, !c3) {
      if (o2 != null)
        for (y3 = {}, _3 = 0; _3 < l3.attributes.length; _3++)
          y3[l3.attributes[_3].name] = l3.attributes[_3].value;
      (v3 || a3) && (v3 && (a3 && v3.__html == a3.__html || v3.__html === l3.innerHTML) || (l3.innerHTML = v3 && v3.__html || ""));
    }
    if (C(l3, p3, y3, r3, c3), v3)
      u3.__k = [];
    else if (_3 = u3.props.children, w(l3, Array.isArray(_3) ? _3 : [_3], u3, i3, t3, r3 && d3 !== "foreignObject", o2, f3, o2 ? o2[0] : i3.__k && k(i3, 0), c3), o2 != null)
      for (_3 = o2.length; _3--; )
        o2[_3] != null && h(o2[_3]);
    c3 || ("value" in p3 && (_3 = p3.value) !== void 0 && (_3 !== y3.value || _3 !== l3.value || d3 === "progress" && !_3) && H(l3, "value", _3, y3.value, false), "checked" in p3 && (_3 = p3.checked) !== void 0 && _3 !== l3.checked && H(l3, "checked", _3, y3.checked, false));
  }
  return l3;
}
function M(n2, u3, i3) {
  try {
    typeof n2 == "function" ? n2(u3) : n2.current = u3;
  } catch (n3) {
    l.__e(n3, i3);
  }
}
function N(n2, u3, i3) {
  var t3, r3;
  if (l.unmount && l.unmount(n2), (t3 = n2.ref) && (t3.current && t3.current !== n2.__e || M(t3, null, u3)), (t3 = n2.__c) != null) {
    if (t3.componentWillUnmount)
      try {
        t3.componentWillUnmount();
      } catch (n3) {
        l.__e(n3, u3);
      }
    t3.base = t3.__P = null;
  }
  if (t3 = n2.__k)
    for (r3 = 0; r3 < t3.length; r3++)
      t3[r3] && N(t3[r3], u3, typeof n2.type != "function");
  i3 || n2.__e == null || h(n2.__e), n2.__e = n2.__d = void 0;
}
function O(n2, l3, u3) {
  return this.constructor(n2, u3);
}
function S(u3, i3, t3) {
  var r3, o2, f3;
  l.__ && l.__(u3, i3), o2 = (r3 = typeof t3 == "function") ? null : t3 && t3.__k || i3.__k, f3 = [], j(i3, u3 = (!r3 && t3 || i3).__k = v(d, null, [u3]), o2 || e, e, i3.ownerSVGElement !== void 0, !r3 && t3 ? [t3] : o2 ? null : i3.firstChild ? n.call(i3.childNodes) : null, f3, !r3 && t3 ? t3 : o2 ? o2.__e : i3.firstChild, r3), z(f3, u3);
}
n = c.slice, l = { __e: function(n2, l3) {
  for (var u3, i3, t3; l3 = l3.__; )
    if ((u3 = l3.__c) && !u3.__)
      try {
        if ((i3 = u3.constructor) && i3.getDerivedStateFromError != null && (u3.setState(i3.getDerivedStateFromError(n2)), t3 = u3.__d), u3.componentDidCatch != null && (u3.componentDidCatch(n2), t3 = u3.__d), t3)
          return u3.__E = u3;
      } catch (l4) {
        n2 = l4;
      }
  throw n2;
} }, u = 0, i = function(n2) {
  return n2 != null && n2.constructor === void 0;
}, _.prototype.setState = function(n2, l3) {
  var u3;
  u3 = this.__s != null && this.__s !== this.state ? this.__s : this.__s = a({}, this.state), typeof n2 == "function" && (n2 = n2(a({}, u3), this.props)), n2 && a(u3, n2), n2 != null && this.__v && (l3 && this.__h.push(l3), m(this));
}, _.prototype.forceUpdate = function(n2) {
  this.__v && (this.__e = true, n2 && this.__h.push(n2), m(this));
}, _.prototype.render = d, t = [], r = typeof Promise == "function" ? Promise.prototype.then.bind(Promise.resolve()) : setTimeout, g.__r = 0, f = 0;

// node_modules/preact/hooks/dist/hooks.module.js
var t2;
var u2;
var r2;
var i2 = [];
var c2 = l.__b;
var f2 = l.__r;
var e2 = l.diffed;
var a2 = l.__c;
var v2 = l.unmount;
function x2() {
  var t3;
  for (i2.sort(function(n2, t4) {
    return n2.__v.__b - t4.__v.__b;
  }); t3 = i2.pop(); )
    if (t3.__P)
      try {
        t3.__H.__h.forEach(g2), t3.__H.__h.forEach(j2), t3.__H.__h = [];
      } catch (u3) {
        t3.__H.__h = [], l.__e(u3, t3.__v);
      }
}
l.__b = function(n2) {
  u2 = null, c2 && c2(n2);
}, l.__r = function(n2) {
  f2 && f2(n2), t2 = 0;
  var r3 = (u2 = n2.__c).__H;
  r3 && (r3.__h.forEach(g2), r3.__h.forEach(j2), r3.__h = []);
}, l.diffed = function(t3) {
  e2 && e2(t3);
  var o2 = t3.__c;
  o2 && o2.__H && o2.__H.__h.length && (i2.push(o2) !== 1 && r2 === l.requestAnimationFrame || ((r2 = l.requestAnimationFrame) || function(n2) {
    var t4, u3 = function() {
      clearTimeout(r3), b2 && cancelAnimationFrame(t4), setTimeout(n2);
    }, r3 = setTimeout(u3, 100);
    b2 && (t4 = requestAnimationFrame(u3));
  })(x2)), u2 = null;
}, l.__c = function(t3, u3) {
  u3.some(function(t4) {
    try {
      t4.__h.forEach(g2), t4.__h = t4.__h.filter(function(n2) {
        return !n2.__ || j2(n2);
      });
    } catch (r3) {
      u3.some(function(n2) {
        n2.__h && (n2.__h = []);
      }), u3 = [], l.__e(r3, t4.__v);
    }
  }), a2 && a2(t3, u3);
}, l.unmount = function(t3) {
  v2 && v2(t3);
  var u3, r3 = t3.__c;
  r3 && r3.__H && (r3.__H.__.forEach(function(n2) {
    try {
      g2(n2);
    } catch (n3) {
      u3 = n3;
    }
  }), u3 && l.__e(u3, r3.__v));
};
var b2 = typeof requestAnimationFrame == "function";
function g2(n2) {
  var t3 = u2, r3 = n2.__c;
  typeof r3 == "function" && (n2.__c = void 0, r3()), u2 = t3;
}
function j2(n2) {
  var t3 = u2;
  n2.__c = n2.__(), u2 = t3;
}

// node_modules/preact/compat/dist/compat.module.js
function S2(n2, t3) {
  for (var e3 in t3)
    n2[e3] = t3[e3];
  return n2;
}
function C2(n2, t3) {
  for (var e3 in n2)
    if (e3 !== "__source" && !(e3 in t3))
      return true;
  for (var r3 in t3)
    if (r3 !== "__source" && n2[r3] !== t3[r3])
      return true;
  return false;
}
function E(n2) {
  this.props = n2;
}
(E.prototype = new _()).isPureReactComponent = true, E.prototype.shouldComponentUpdate = function(n2, t3) {
  return C2(this.props, n2) || C2(this.state, t3);
};
var w2 = l.__b;
l.__b = function(n2) {
  n2.type && n2.type.__f && n2.ref && (n2.props.ref = n2.ref, n2.ref = null), w2 && w2(n2);
};
var R = typeof Symbol != "undefined" && Symbol.for && Symbol.for("react.forward_ref") || 3911;
var A3 = l.__e;
l.__e = function(n2, t3, e3) {
  if (n2.then) {
    for (var r3, u3 = t3; u3 = u3.__; )
      if ((r3 = u3.__c) && r3.__c)
        return t3.__e == null && (t3.__e = e3.__e, t3.__k = e3.__k), r3.__c(n2, t3);
  }
  A3(n2, t3, e3);
};
var O2 = l.unmount;
function L2() {
  this.__u = 0, this.t = null, this.__b = null;
}
function U(n2) {
  var t3 = n2.__.__c;
  return t3 && t3.__e && t3.__e(n2);
}
function M2() {
  this.u = null, this.o = null;
}
l.unmount = function(n2) {
  var t3 = n2.__c;
  t3 && t3.__R && t3.__R(), t3 && n2.__h === true && (n2.type = null), O2 && O2(n2);
}, (L2.prototype = new _()).__c = function(n2, t3) {
  var e3 = t3.__c, r3 = this;
  r3.t == null && (r3.t = []), r3.t.push(e3);
  var u3 = U(r3.__v), o2 = false, i3 = function() {
    o2 || (o2 = true, e3.__R = null, u3 ? u3(l3) : l3());
  };
  e3.__R = i3;
  var l3 = function() {
    if (!--r3.__u) {
      if (r3.state.__e) {
        var n3 = r3.state.__e;
        r3.__v.__k[0] = function n4(t5, e4, r4) {
          return t5 && (t5.__v = null, t5.__k = t5.__k && t5.__k.map(function(t6) {
            return n4(t6, e4, r4);
          }), t5.__c && t5.__c.__P === e4 && (t5.__e && r4.insertBefore(t5.__e, t5.__d), t5.__c.__e = true, t5.__c.__P = r4)), t5;
        }(n3, n3.__c.__P, n3.__c.__O);
      }
      var t4;
      for (r3.setState({ __e: r3.__b = null }); t4 = r3.t.pop(); )
        t4.forceUpdate();
    }
  }, c3 = t3.__h === true;
  r3.__u++ || c3 || r3.setState({ __e: r3.__b = r3.__v.__k[0] }), n2.then(i3, i3);
}, L2.prototype.componentWillUnmount = function() {
  this.t = [];
}, L2.prototype.render = function(n2, t3) {
  if (this.__b) {
    if (this.__v.__k) {
      var e3 = document.createElement("div"), r3 = this.__v.__k[0].__c;
      this.__v.__k[0] = function n3(t4, e4, r4) {
        return t4 && (t4.__c && t4.__c.__H && (t4.__c.__H.__.forEach(function(n4) {
          typeof n4.__c == "function" && n4.__c();
        }), t4.__c.__H = null), (t4 = S2({}, t4)).__c != null && (t4.__c.__P === r4 && (t4.__c.__P = e4), t4.__c = null), t4.__k = t4.__k && t4.__k.map(function(t5) {
          return n3(t5, e4, r4);
        })), t4;
      }(this.__b, e3, r3.__O = r3.__P);
    }
    this.__b = null;
  }
  var u3 = t3.__e && v(d, null, n2.fallback);
  return u3 && (u3.__h = null), [v(d, null, t3.__e ? null : n2.children), u3];
};
var T3 = function(n2, t3, e3) {
  if (++e3[1] === e3[0] && n2.o.delete(t3), n2.props.revealOrder && (n2.props.revealOrder[0] !== "t" || !n2.o.size))
    for (e3 = n2.u; e3; ) {
      for (; e3.length > 3; )
        e3.pop()();
      if (e3[1] < e3[0])
        break;
      n2.u = e3 = e3[2];
    }
};
(M2.prototype = new _()).__e = function(n2) {
  var t3 = this, e3 = U(t3.__v), r3 = t3.o.get(n2);
  return r3[0]++, function(u3) {
    var o2 = function() {
      t3.props.revealOrder ? (r3.push(u3), T3(t3, n2, r3)) : u3();
    };
    e3 ? e3(o2) : o2();
  };
}, M2.prototype.render = function(n2) {
  this.u = null, this.o = new Map();
  var t3 = A(n2.children);
  n2.revealOrder && n2.revealOrder[0] === "b" && t3.reverse();
  for (var e3 = t3.length; e3--; )
    this.o.set(t3[e3], this.u = [1, 0, this.u]);
  return n2.children;
}, M2.prototype.componentDidUpdate = M2.prototype.componentDidMount = function() {
  var n2 = this;
  this.o.forEach(function(t3, e3) {
    T3(n2, e3, t3);
  });
};
var j3 = typeof Symbol != "undefined" && Symbol.for && Symbol.for("react.element") || 60103;
var P2 = /^(?:accent|alignment|arabic|baseline|cap|clip(?!PathU)|color|dominant|fill|flood|font|glyph(?!R)|horiz|marker(?!H|W|U)|overline|paint|stop|strikethrough|stroke|text(?!L)|underline|unicode|units|v|vector|vert|word|writing|x(?!C))[A-Z]/;
var V = typeof document != "undefined";
var z2 = function(n2) {
  return (typeof Symbol != "undefined" && typeof Symbol() == "symbol" ? /fil|che|rad/i : /fil|che|ra/i).test(n2);
};
function B2(n2, t3, e3) {
  return t3.__k == null && (t3.textContent = ""), S(n2, t3), typeof e3 == "function" && e3(), n2 ? n2.__c : null;
}
_.prototype.isReactComponent = {}, ["componentWillMount", "componentWillReceiveProps", "componentWillUpdate"].forEach(function(n2) {
  Object.defineProperty(_.prototype, n2, { configurable: true, get: function() {
    return this["UNSAFE_" + n2];
  }, set: function(t3) {
    Object.defineProperty(this, n2, { configurable: true, writable: true, value: t3 });
  } });
});
var H2 = l.event;
function Z() {
}
function Y() {
  return this.cancelBubble;
}
function q2() {
  return this.defaultPrevented;
}
l.event = function(n2) {
  return H2 && (n2 = H2(n2)), n2.persist = Z, n2.isPropagationStopped = Y, n2.isDefaultPrevented = q2, n2.nativeEvent = n2;
};
var G;
var J = { configurable: true, get: function() {
  return this.class;
} };
var K = l.vnode;
l.vnode = function(n2) {
  var t3 = n2.type, e3 = n2.props, r3 = e3;
  if (typeof t3 == "string") {
    var u3 = t3.indexOf("-") === -1;
    for (var o2 in r3 = {}, e3) {
      var i3 = e3[o2];
      V && o2 === "children" && t3 === "noscript" || o2 === "value" && "defaultValue" in e3 && i3 == null || (o2 === "defaultValue" && "value" in e3 && e3.value == null ? o2 = "value" : o2 === "download" && i3 === true ? i3 = "" : /ondoubleclick/i.test(o2) ? o2 = "ondblclick" : /^onchange(textarea|input)/i.test(o2 + t3) && !z2(e3.type) ? o2 = "oninput" : /^onfocus$/i.test(o2) ? o2 = "onfocusin" : /^onblur$/i.test(o2) ? o2 = "onfocusout" : /^on(Ani|Tra|Tou|BeforeInp)/.test(o2) ? o2 = o2.toLowerCase() : u3 && P2.test(o2) ? o2 = o2.replace(/[A-Z0-9]/, "-$&").toLowerCase() : i3 === null && (i3 = void 0), r3[o2] = i3);
    }
    t3 == "select" && r3.multiple && Array.isArray(r3.value) && (r3.value = A(e3.children).forEach(function(n3) {
      n3.props.selected = r3.value.indexOf(n3.props.value) != -1;
    })), t3 == "select" && r3.defaultValue != null && (r3.value = A(e3.children).forEach(function(n3) {
      n3.props.selected = r3.multiple ? r3.defaultValue.indexOf(n3.props.value) != -1 : r3.defaultValue == n3.props.value;
    })), n2.props = r3, e3.class != e3.className && (J.enumerable = "className" in e3, e3.className != null && (r3.class = e3.className), Object.defineProperty(r3, "className", J));
  }
  n2.$$typeof = j3, K && K(n2);
};
var Q = l.__r;
l.__r = function(n2) {
  Q && Q(n2), G = n2.__c;
};

// src/settings.tsx
var SERVER_ADDRESS_CHANGED = "server-address-changed";
var CONTAINER_HEIGHT_CHANGED = "container-height-changed";
var DEFAULT_SETTINGS = {
  address: "http://localhost:8080",
  containerHeight: "90%",
  autoContainerHeight: true
};
var CalibreSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calibre Settings" });
    new import_obsidian.Setting(containerEl).setName("Server Address").setDesc("The address of calibre Content server.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder(DEFAULT_SETTINGS.address).setValue(this.plugin.settings.address).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.address = value;
        yield this.plugin.saveSettings(SERVER_ADDRESS_CHANGED);
      }));
    });
    new import_obsidian.Setting(containerEl).setName("Auto Container Height").setDesc("When toggle on, Container Height will be ignored.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoContainerHeight).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.autoContainerHeight = value;
        yield this.plugin.saveSettings(CONTAINER_HEIGHT_CHANGED);
      }));
    });
    new import_obsidian.Setting(containerEl).setName("Container Height").setDesc("Change default height of the container, percent or height with a valid CSS unit. e.g., 90%, 860px.").addText((text) => {
      text.setPlaceholder(DEFAULT_SETTINGS.containerHeight).setValue(this.plugin.settings.containerHeight).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.containerHeight = value;
        yield this.plugin.saveSettings(CONTAINER_HEIGHT_CHANGED);
      }));
    });
    if (import_obsidian.Platform.isDesktopApp) {
      B2(/* @__PURE__ */ v(d, null, /* @__PURE__ */ v("p", null, "Make a donation to support Calibre plugin development."), /* @__PURE__ */ v("p", null, "\u2764\uFE0F Thank you for your support. \u2764\uFE0F"), /* @__PURE__ */ v("a", {
        href: "https://paypal.me/caronchenhz",
        className: "paypal"
      }, /* @__PURE__ */ v("svg", {
        width: "145px",
        height: "37px",
        viewBox: "0 0 145 37",
        version: "1.1",
        xmlns: "http://www.w3.org/2000/svg",
        xmlnsXlink: "http://www.w3.org/1999/xlink"
      }, /* @__PURE__ */ v("defs", null, /* @__PURE__ */ v("polygon", {
        id: "path-1",
        points: "0 0.30377 29.7890799 0.30377 29.7890799 36.629778 0 36.629778"
      }), /* @__PURE__ */ v("polygon", {
        id: "path-3",
        points: "0 0.30377 27.0026179 0.30377 27.0026179 32.599368 0 32.599368"
      }), /* @__PURE__ */ v("polygon", {
        id: "path-5",
        points: "0 0.30377 27.0025944 0.30377 27.0025944 32.599368 0 32.599368"
      })), /* @__PURE__ */ v("g", {
        id: "Page-1",
        stroke: "none",
        strokeWidth: "1",
        fill: "none",
        fillRule: "evenodd"
      }, /* @__PURE__ */ v("g", {
        id: "01.2---Corp-Landing---Sticky-Nav",
        transform: "translate(-80.000000, -21.000000)"
      }, /* @__PURE__ */ v("g", {
        id: "logo-paypal",
        transform: "translate(80.000000, 21.000000)"
      }, /* @__PURE__ */ v("path", {
        d: "M112.489747,16.203225 C112.054389,19.158415 109.870796,19.158415 107.758093,19.158415 L106.556562,19.158415 L107.399352,13.640975 C107.450549,13.307605 107.728735,13.061925 108.055253,13.061925 L108.606253,13.061925 C110.04408,13.061925 111.402426,13.061925 112.102364,13.908485 C112.521611,14.415015 112.647994,15.165745 112.489747,16.203225 M111.570698,8.493535 L103.60429,8.493535 C103.059735,8.493535 102.595735,8.903125 102.511241,9.458865 L99.2897346,30.568475 C99.2260062,30.985095 99.5374877,31.362125 99.9456358,31.362125 L104.033204,31.362125 C104.414142,31.362125 104.739228,31.075005 104.798302,30.686135 L105.711623,24.701385 C105.796833,24.145275 106.260475,23.735315 106.805031,23.735315 L109.325525,23.735315 C114.572735,23.735315 117.600907,21.111645 118.3925,15.910185 C118.748735,13.635425 118.406821,11.847955 117.376068,10.596615 C116.243278,9.220955 114.235475,8.493535 111.570698,8.493535",
        id: "Fill-1",
        fill: "#009CDE"
      }), /* @__PURE__ */ v("path", {
        d: "M55.6725531,16.203225 C55.2371951,19.158415 53.0532444,19.158415 50.9412568,19.158415 L49.7393679,19.158415 L50.582158,13.640975 C50.6333556,13.307605 50.9115407,13.061925 51.2380593,13.061925 L51.7890593,13.061925 C53.2268864,13.061925 54.5852321,13.061925 55.2851704,13.908485 C55.7040593,14.415015 55.8308,15.165745 55.6725531,16.203225 M54.7535037,8.493535 L46.7870963,8.493535 C46.2425407,8.493535 45.7788988,8.903125 45.6936889,9.458865 L42.4725407,30.568475 C42.4091704,30.985095 42.7206519,31.362125 43.128442,31.362125 L46.9320963,31.362125 C47.4766519,31.362125 47.9402938,30.952165 48.0255037,30.396055 L48.8944296,24.701385 C48.9792815,24.145275 49.4432815,23.735315 49.987837,23.735315 L52.5086889,23.735315 C57.7555407,23.735315 60.7840716,21.111645 61.5753062,15.910185 C61.9315407,13.635425 61.5896272,11.847955 60.5592321,10.596615 C59.426084,9.220955 57.4182815,8.493535 54.7535037,8.493535",
        id: "Fill-3",
        fill: "#003087"
      }), /* @__PURE__ */ v("path", {
        d: "M73.2472333,23.781713 C72.8788259,26.034273 71.1484926,27.546093 68.9416284,27.546093 C67.8353321,27.546093 66.949579,27.178313 66.3803198,26.482343 C65.8160728,25.791923 65.6034062,24.808093 65.7824185,23.712893 C66.1261222,21.480683 67.8840235,19.919653 70.0572333,19.919653 C71.140616,19.919653 72.0199247,20.291133 72.6002827,20.994133 C73.184579,21.701943 73.4144309,22.692063 73.2472333,23.781713 M78.563184,16.108653 L74.7487889,16.108653 C74.4219123,16.108653 74.1437272,16.354333 74.0925296,16.688073 L73.9253321,17.790303 L73.6582457,17.391073 C72.8322827,16.151573 70.9913198,15.737913 69.1525049,15.737913 C64.9385543,15.737913 61.338616,19.038313 60.6379617,23.667013 C60.2731346,25.976553 60.7908383,28.183233 62.0578877,29.723543 C63.222184,31.138793 64.8830605,31.727833 66.862221,31.727833 C70.2588012,31.727833 72.1430852,29.472683 72.1430852,29.472683 L71.9726654,30.568253 C71.908937,30.984873 72.2204185,31.361903 72.6285667,31.361903 L76.0638136,31.361903 C76.6083691,31.361903 77.0720111,30.952683 77.156863,30.396573 L79.2190852,16.901563 C79.2824556,16.485313 78.9709741,16.108653 78.563184,16.108653",
        id: "Fill-5",
        fill: "#003087"
      }), /* @__PURE__ */ v("path", {
        d: "M130.064427,23.781713 C129.69602,26.034273 127.966044,27.546093 125.75918,27.546093 C124.652526,27.546093 123.766773,27.178313 123.197156,26.482343 C122.633267,25.791923 122.4206,24.808093 122.599612,23.712893 C122.943316,21.480683 124.701217,19.919653 126.874427,19.919653 C127.957452,19.919653 128.837119,20.291133 129.417477,20.994133 C130.001773,21.701943 130.231625,22.692063 130.064427,23.781713 M135.380378,16.108653 L131.565983,16.108653 C131.239106,16.108653 130.960921,16.354333 130.909723,16.688073 L130.742526,17.790303 L130.47544,17.391073 C129.649477,16.151573 127.808156,15.737913 125.969699,15.737913 C121.755748,15.737913 118.15581,19.038313 117.455156,23.667013 C117.090686,25.976553 117.608032,28.183233 118.875081,29.723543 C120.03902,31.138793 121.700254,31.727833 123.679415,31.727833 C127.075995,31.727833 128.960279,29.472683 128.960279,29.472683 L128.789859,30.568253 C128.726131,30.984873 129.037612,31.361903 129.44576,31.361903 L132.881007,31.361903 C133.425563,31.361903 133.889205,30.952683 133.974057,30.396573 L136.036279,16.901563 C136.099649,16.485313 135.788168,16.108653 135.380378,16.108653",
        id: "Fill-7",
        fill: "#009CDE"
      }), /* @__PURE__ */ v("path", {
        d: "M98.8795457,16.108727 L95.0454593,16.108727 C94.678842,16.108727 94.3358543,16.296687 94.1296321,16.610077 L88.8408914,24.660167 L86.5992988,16.924947 C86.4593111,16.440617 86.0278914,16.108727 85.5391877,16.108727 L81.7702617,16.108727 C81.3148543,16.108727 80.9951383,16.571227 81.1415704,17.016707 L85.3633975,29.823147 L81.3925457,35.613277 C81.0807062,36.068007 81.3954099,36.696267 81.9345951,36.696267 L85.7647432,36.696267 C86.1277802,36.696267 86.4675457,36.512377 86.674484,36.204167 L99.4251753,17.186167 C99.7302123,16.731067 99.4151506,16.108727 98.8795457,16.108727",
        id: "Fill-9",
        fill: "#003087"
      }), /* @__PURE__ */ v("path", {
        d: "M139.876523,9.07314 L136.606684,30.56903 C136.543314,30.98565 136.855153,31.36194 137.262585,31.36194 L140.551042,31.36194 C141.095598,31.36194 141.55924,30.95235 141.644091,30.39661 L144.867746,9.287 C144.931474,8.87038 144.619993,8.49372 144.211844,8.49372 L140.532425,8.49372 C140.205548,8.49372 139.927363,8.7394 139.876523,9.07314",
        id: "Fill-11",
        fill: "#009CDE"
      }), /* @__PURE__ */ v("g", {
        id: "Group-15",
        transform: "translate(0.000000, 0.066415)"
      }, /* @__PURE__ */ v("mask", {
        id: "mask-2",
        fill: "white"
      }, /* @__PURE__ */ v("use", {
        xlinkHref: "#path-1"
      })), /* @__PURE__ */ v("g", {
        id: "Clip-14"
      }), /* @__PURE__ */ v("path", {
        d: "M26.8450852,9.532828 C27.2739988,6.706768 26.842221,4.784248 25.363221,3.042288 C23.7349247,1.124948 20.7933938,0.303548 17.0294802,0.303548 L6.10471481,0.303548 C5.33567778,0.303548 4.68085062,0.881858 4.56091235,1.667368 L0.0114925926,31.479008 C-0.0780135802,32.067308 0.361998765,32.599368 0.938060494,32.599368 L7.68252963,32.599368 L7.21709753,35.650018 C7.13869012,36.164688 7.52320864,36.629778 8.02730741,36.629778 L13.7120235,36.629778 C14.3851099,36.629778 14.9579494,36.123988 15.0628506,35.437268 L15.1187025,35.138308 L16.1895543,28.120148 L16.2586531,27.732388 C16.3635543,27.045668 16.9363938,26.539508 17.6091222,26.539508 L18.4594309,26.539508 C23.9669247,26.539508 28.2793321,24.227378 29.539221,17.539998 C30.0658753,14.745388 29.7934185,12.413278 28.4014185,10.773438 C27.9800235,10.277268 27.4562333,9.867308 26.8450852,9.532828",
        id: "Fill-13",
        fill: "#009CDE",
        mask: "url(#mask-2)"
      })), /* @__PURE__ */ v("g", {
        id: "Group-18",
        transform: "translate(0.000000, 0.066415)"
      }, /* @__PURE__ */ v("mask", {
        id: "mask-4",
        fill: "white"
      }, /* @__PURE__ */ v("use", {
        xlinkHref: "#path-3"
      })), /* @__PURE__ */ v("g", {
        id: "Clip-17"
      }), /* @__PURE__ */ v("path", {
        d: "M26.8450852,9.532828 C27.2739988,6.706768 26.842221,4.784248 25.363221,3.042288 C23.7349247,1.124948 20.7933938,0.303548 17.0294802,0.303548 L6.10471481,0.303548 C5.33567778,0.303548 4.68085062,0.881858 4.56091235,1.667368 L0.0114925926,31.479008 C-0.0780135802,32.067308 0.361998765,32.599368 0.938060494,32.599368 L7.68252963,32.599368 L9.37670247,21.496778 L9.32407284,21.844948 C9.44401111,21.059808 10.0931099,20.481498 10.8625049,20.481498 L14.0679,20.481498 C20.3634062,20.481498 25.2930481,17.838218 26.7333815,10.194018 C26.7759864,9.967578 26.8125049,9.748538 26.8450852,9.532828",
        id: "Fill-16",
        fill: "#012169",
        mask: "url(#mask-4)"
      })), /* @__PURE__ */ v("g", {
        id: "Group-21",
        transform: "translate(0.000000, 0.066415)"
      }, /* @__PURE__ */ v("mask", {
        id: "mask-6",
        fill: "white"
      }, /* @__PURE__ */ v("use", {
        xlinkHref: "#path-5"
      })), /* @__PURE__ */ v("g", {
        id: "Clip-20"
      }), /* @__PURE__ */ v("path", {
        d: "M11.196721,9.570198 C11.268684,9.098078 11.5622642,8.711058 11.9571654,8.515698 C12.1365358,8.426898 12.3370296,8.377318 12.5471901,8.377318 L21.1107827,8.377318 C22.1254247,8.377318 23.0713259,8.445768 23.9363136,8.590068 C24.1833506,8.630768 24.4239432,8.678128 24.6573753,8.731778 C24.8911654,8.785428 25.1177951,8.845368 25.3372642,8.911598 C25.4471778,8.944898 25.5549432,8.979678 25.6612765,9.015938 C26.0858938,9.161718 26.4811531,9.333398 26.8452642,9.532828 C27.2738198,6.706768 26.842042,4.783878 25.363042,3.042288 C23.7351037,1.124948 20.7932148,0.303548 17.0296593,0.303548 L6.10489383,0.303548 C5.33549877,0.303548 4.6806716,0.881858 4.56073333,1.667368 L0.0116716049,31.479008 C-0.0781925926,32.067308 0.361819753,32.599368 0.937881481,32.599368 L7.68270864,32.599368 L9.37688148,21.496778 L11.196721,9.570198 Z",
        id: "Fill-19",
        fill: "#003087",
        mask: "url(#mask-6)"
      })))))))), containerEl.createDiv({ cls: "calibre-donation" }));
    }
  }
};

// src/tools.ts
var CALIBRE_CONTAINER_FILE_IDENTIFIER = "THIS IS A GENERATED CALIBRE CONTAINER FILE BY CALIBRE PLUGIN. DO NOT EDIT.";
function calibreContainer(address) {
  return `<!--
${CALIBRE_CONTAINER_FILE_IDENTIFIER}
-->
<div class="calibre-container"><iframe src="${address}"></iframe></div>`;
}
var CALIBRE_ICON_ID = "calibre";
var CALIBRE_ICON_SVG = `
<g transform="translate(-24.920761,-148.42979)">
	<image width="100" height="100" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA5CAYAAACMGIOFAAAACXBIWXMAABYlAAAWJQFJUiTwAAAU
	BklEQVRoge2aaWxk2XXff+fe92onWWSRLC7NbrK7p6d7emZ6RiNZYy2j2AqCSeLYQGAktqMEgQ0k
	gT/4SwI4XwwjQZDYCZDAcIwYhr/YsaMPQgLYGW2WMtJI1hKNPKPp2Vq9kt3ct2JtrOW9e08+vKpu
	LsVWj90B8iEHKBBVfPfd+7/nnP8595wrHBYRMDyiKPjkz48WETEoFlR74/yjzvNXFXt0LTxY+KN8
	5APMpb13exHUGDGZIBgpZtLnjRHpOt/8gO97ZAkOfTFkhgIu6o+eTADXiHk/9nR+xINGwY9lM5dm
	c/mfy9ngVNbYMxmxpzLWjOdNUKpo95UvLN/7OyjCI1rGB5GgtxCr4J4d5TcWhvmVyOPkuJbvi4IL
	DfZWjX//gx1+tT/+BJgG1D9ZGP7Fy/niv+g6Fxsl8F6JIu+7cYTgz4XGSOS8T5bzeIEGHHhjPuSs
	8+AUlYdMpOCNxw6FnD84/sSngXqne3c3atHyLhYjEqStZPIhw8UccxOZyW9/a2e00mjvioA+Zl32
	NdlfqLMGvEfkISarINYkGkUMRghOMnEjYp1zcVhKL3/8U+fIjoTheDlnx8azDBfTmh9Kkc+Ho1/+
	pbsTlRvtXRER1ccLs69JBbi2x9DdBvgfPYUYgWZMDvV4JeYkczXiAbKj9vZnfvlZmu3IouC94mIv
	UeQ9HjNZys+8e2P7hw/b3L+sHCKeoZB4OAXuBLUcpFMjYI24iSs//rOFoaEr3rkWIseGiUDkIJ2J
	Gqtrtb10Kix6VRVBQFBVH4bGLMyNnPnadyF5x+O11z5IAZgr0J7MQuTB9NZ70HKsMXivKIh4pZMf
	HSt9+uXfCgM70zOxgXujiAQSbUastnNWUS/HHpyeKCw8VmQH5JAmY49EDmIg7ijqIJUVjIBzSrXm
	yWTBBAIOHNhOu+VdsvfxSSBFJGx2u7Vqo9sYy6emYqdKH6cI3itTE4X55OnHHkGOZzcigotgYrrI
	9IUZuh2lXlPCVMiLLz9PujiEOsUIiKIiYsUaEBMgMvBjAku766LNnebdwBoOEouAOKeUS7k5AK/6
	2DOhYyCNEbpteOqFC5w5O8Xs6RJ/8zN/jdh5xosZzl48Q6eV+JqIiBiDiMFaQ2AtQRAQ9j5BEGCt
	JbCWOFa/tFJbtFYOeZwIEsWOmcnCqXwutKp4OW7NfyUJjv6gqgQB7O7U+N53VigEHc5FXe4uOV7/
	1j0mZjMYC95DvlAw0xMTJmWFbCZDNp0mnU4RGEPsHO1ul1a7Q+xj4o6aje39u8eXIBI7ZbiQniwO
	Zcaa+9HW484HjoEUEaJIKZXy/Mbv/iNqOzUmp0Z59so8s2cm+aPf+xLeg7HQaNT96uaGD405viTV
	+78FgWV7ryqtjdodr8rBMCGCeO/JZcOR8bHs5MpGfUsEOTD88YNUVYIUbC5v89r/+AaN6j6xV6wR
	CsM5quu7BCGH0nRFH8oXqmCtCde2msvdyHsROeQmXvGplDXlUv4U8O7/dXP1Xkln4N03lvhmJYmZ
	o8PQbMDoRJ7p+dwHnkRRwsCEqxv19VqjU8nnMiXnvPbBqKoPjJizp4vzAMKjxcpHzY6OE48IcQSl
	iRy//Qef4Td//xewQ1me/cgk//H3/yFjxTxx/IFRElgT7NU6lWqtsxVY4WCs6HvgzGQSRgasWkCM
	iLHGBoEYGwCiqioDEpCjctwnjdBuKx/+2BO8/ufvc+/WOv/8X77M1GSBP/ovf8ab31mkMGzw3Udn
	egWMEdNsdRuVWntl4bS5qIreX54Izinl8fyZ5Ksxxpok5fReVb0DVVVFne+t05BK59PddqP7gUH2
	2bVaa3F7aZed9T0ubVb57B9+k047YvrsKDsrFcJHrh8kKI0R0+3Eur7VWAqsuZ8vQz9WeibH8qcB
	4jiOOPh/YwJrSzNDpfnzT338bzxVXvjQs6NT554anXriwp/81s//7I3X//QbYqxV7wbmzwPZ1cVK
	NmP5tV//KSo7DVDl0j97ifGZUX7nt19l/U6F9AdyTUUEwXsWl6uL1vbPU/2kRyRynqnx7HR5amrE
	Dp8/MzX/zOXp8y88kx2eeebV/7p8sd2cncsVbfqlv/9RssNFOvtRnBsKg3PP//WfuPH6n35DROQk
	5xxAPEnq9u6bd3n1i9fBOUwAuxUYL4WMlQJSmSROfkBRgNWtxtLRfyRhBLJp8r/4r/7nK2bmw59I
	Wa+IEe8cr3/hOzSrEdWtbb96c8mfulQkanvfCWFs6tJzkJj1SRMfNzoFG8DGWpNnPzzN2PwoE9PD
	/Nq/+0kWrsywvNoiFZq/ZIopbG7vLzmvcDiMiPeQCckXh6XUaUGrFsfNShyrN644abxqV12UNrWd
	/SAICMQEgYtgcv7K5Uy+GKh6dxIJHdOkMcJ+XXnxY7P841/6KLcXK4TpgMrqHj/98jm2VndobDUI
	jm6PKl4VYwY7qyqKNWZtq7Hc6cRqEpD3bVYRrLh00PjhMsUXLhlrAxUjNhDGpgugVbwPqaw3kl0R
	I95BbmTizMjE6dPt5t5tRIQBIeU48ZDkpUOjWf7JP/0CuRCuvDjLH3zuJh97apTJ6Rx76w3CfgVI
	erE1DEmnU9Sb+yeAVA0CE6xuNraq9U6lkAvHYqf0915V1QZBmOnebsQxrXRosr3NoTRTQIwHSVFZ
	b+HiCCQU72KXywepyfnnntpYvHpbMKIDKp0DiCfxN6Oef/NvP0Gj3mF4OM3HX5yiNJ7js599+7Cp
	KhgrdOOY4UKB4XKBdCrFdmWPSq2GfaBZtdYEtXqrtlfvbIwMpcdiFyv3YXpvbMoGnaVO1NrfknTu
	tDivPhYZLQ8RpAQXW6pbEd12kyAs4ryqCEyf+9Bzb3/9D1/hhExpQAiBIICN1RrfffUGtVobRFCF
	YjFDt97CnFDH29jZYWFulnwmw541h86GmoQR2/FQqbaXz86NXDoUKxUwITm2w05j464pLZwmQp1D
	hko5sgVLYw8ae8p+rUZxsoiLRZyD8VOXn4eTyec4SK+k0/DetR2++vXtpC7Z024QCOUypFKCxsff
	Z6yl1e5QLBQwxuBVCQ7srekRw+pmfemjdppDSbioKJZCqjlSX33nlpxd+AQkaUB2KMNQKUW94mg3
	DfWdKmNTgIi4CMbnnr6czg7bTqvmBvnlYOJpKJ/61BSXr0xR3WsRBJY49kxO5vjyV5a4dnWbXPr4
	jqn3GBGstWQzaQJr8V4xNjHZvtbuLFcXjRH0QNVIEGKnjI+Ek+7ardcSnSjqlTBrGS3nWLleJY5C
	Khs15p9J3uhiGBqdmi+W5+c2Fq8uDspnB1KhCMRdR1RvETU6dOst2rUWu2s1JI6RAaP6+WcQBATW
	UsjlmJmcQJOj1SHZ2Gou9sYcOnI55xnKZ6a6O+8vRxGIGKualKfHpvOgDj3IsBjx3vkwQ3p87vKl
	/m9H1zbwFJLJwBtvbvH1b2wmGlJIp4TpM1mqlQ6p8IRSjCrFoSE63YgbS/fIZzIY8yCm9s1zbaux
	FMeeI3FNnPfkC/kJX79Za9bbmyNDmUkfeVUvUpoZQqxHSFNZb+KiDkgavHpjMDPnP/L8u9/87BcH
	kc+JGaiIMlEyTJQMk+OGQgF+4sVJzp0r0u48ML1k9dwPJTt7ezjvmSqNsbm723tODz7J1u7+Wjdy
	kTyIlb0N9i6TyUjBVEx1e/m6TVSgzkGxnCeVFhBDbTui02rSI+6EfOaePpF8BpsrSXBe3/ZsbHu2
	djz3VpUvfXULFzuO5hVJNcGxMDdLu9NhpJBPOj3mcGbU95X17ebWXr2zG1g5Go40CFOUh7vFjcWr
	V4NUsurE7/JkhwIEaNagWa1hbJL3ughKsxefDtN5o+rd0frvQOJpNZRPfnyUJy8VqVa7BIEQx8qp
	mRxffW1zsKlKQjzOexZX1zhVniSKYla3tgmD4IEagb1ap1apttfGRjLlyMUqB7ZNESZGw7lvLb/9
	pjF/FwDvIFNIMzKeprLepVk11HdrjJ9KttjFMDw+Nz86dXZuc+ntpaPkM9hcBXzskG6EdGOkG2Pj
	mNZei24r4mjmpiSF57WtbeamyszPTrPfbie7aO0DRu/5ZBw7tnb3l23SUHlwpOqRT3l86PzO3bfe
	jeOkeauqhGlDYbTA1MIKpZmI9duVXrwW8d75VIZMafbiQPI5kXj+4mqV175dRQScg1od8gXD6TlL
	EHDUDLHWour5wbXrzJYn2avVaXU6BNYesp6kXItu7uwv2cRcD8RKJIpjpiZHzzc237/bariWsTbr
	4iSjHz8VMXthgrNXfpxbP3iDuJu4ivbIZ/bCi8+//+3Pfeko+ZxMPArZTKKl4qjhZ/7WML/zmwuc
	O5+n3eaQNoXkiDY/O8v503O0Ox1SYXAwpTsmi8t7i0kr4hBGiSLHVLk4F8bbtb3tlZs2ADFotwVP
	f/IJnnjhY4xMjvHsp14ijpKmjYiIdzBx+pmB5HNMk/2GurHCqZkUL/3YMB+9UmB9K+LVr22zudIi
	lYJDdW4R1HvuLK/wwuVLXDq3wObOLv/76jukU6mBIFc2G3d61nAwVuKcpzicL+dsM7V25+oPZuZP
	PxN11HuPyQ6XAIg6ikjq4ECJ75NPTqLO/qHMZ0CbADpduLCQ5j/86imcKr/739b5z3+8xedeqbKy
	1iUVysD2Xiad5u3rN1nd2KLd7fYaVMcrsgDrW417sfPIsXOl+nQmNMWCKa/c/IvvmeBB00ldkgEd
	PTaKmPvkUyyfnevhvv/QMZDqIZ2G92+2+ZVfX+TW7SYvPJPhyqWQkZIQphOAg46nzjlOT5cZyufo
	dLtJCBmEkCRWtjtx2xyxWVXVwBpOTQ2f3Vh85/Xe2e9AXjjwoCGakE+2NPNkj3weAvLB7sDmtuP1
	N1t86atVtOP45X9Q5MKFNO22Huav3mG52WpRb7bY2auysb17v/03SNa3mtuVans7aQBxOFriOb9Q
	vrB+58332k1iY44caQaIqnpjYOaJjzzXA/AQkP19FQizQpiCnarnK3/e4r+/UmN7MyIMj3Sj5QHD
	drpd0qkUc1Plh63J1Oqd1s5eay0IDne5QPDOMzsz9mS0d7feqKwu2gCOJt3Hli2CdzA5/9yHEtD+
	5DhpBPbb8OKVFD/zkxmiGEILuSzkcyC9Zs8hHWmvyuccYRgQBJa7a+uDKhHJHEaMAjuV1j1rj/oX
	EjvPTHnkHERsL19724Zw4sseDDRxDKWZJ58Owoyof5D5HPdJILAQq/KVb3WS+mqPP1ThiXlLN+bw
	SaQHcKRQQL2yvr3DmdlpSsUi3vsBRJH8sLHTXLLmsLmKIHHsmRgrnAJYvvH69x9Rk+IiGJmYXxid
	PpfkQpwAEhJNua7HpmCnClEEWxWYnxEKKT+4HCmC10TFURyTDlN49QMV0Md8++7enSMJPCASx57x
	sezkWB6zevutw+TzEJjeO5/Kki3NXLzYBz4QpCqEIdxc8vzcp4VPviiUy8Iv/G3D3/u08P23HNmM
	cKwfrIqIYXJsjPmZae6urVGp1nqZ0BGgPc2tbNQXvfZLZw82wHklnwlGpyYLcys33rja3Sd6FPLh
	BPI5scaztad88TXPz78sjI1ApwP/6Y9jlreUXCZpuR+o4GCNoRtF7NXrLK6ukstkSIUhURwfU0K/
	RbC5u78SRx4RDsfK3o2QqfLo2ffu3P5ao7K6VCjNnI+jhzd4+uRTPkI+hy4rWUEDA+pgKANLa8q/
	/j0lm4ZWJ9HwcBach9CACnhVvFe8gsaOlY1NvPfU6k2M6SUdveSj73p9H9za2V9rdeKGMVLoLUFU
	wXvvBTUz5ZEFuPe1vc1b742UZ87H3QFlhsMoTRzD6PSFp22YwkVdh4gcuqx0vUphZf9BeBBJ2Na3
	e0TTAV/vlUciKFkjL5VGJZPJkEmlyGbSpMMQay3OOdrdiHanTSeKqdVqGDH9fiQAGzvNne3d/a3y
	eL4QxV6tFbGBIQiFfCHF5Yvls/zJO6zeeP3Ns89/8qdVVR+O8QD5TJ2f3b733or0QfYlbfEZO+BG
	1oFCcv9v6MGK1716Q01zHyOCGMH0TFN7RSjvPSpCt906yJAKSHM/6jY70VpxNLNQrXW023HU9tpU
	dlpcq2+zdrO+ALCx9NYbyciH9iJVFfWuG2fyqfzY9IUnt++9tyIY6ZurKHBmiP1y77LSQzubAuKg
	k0Hb3QhrhX7s1QeP3BdjLFHsDp+qBKOK+7PP315+77UN7i5VtVbp0NjraHs/Vu16msbPAKzffuvd
	TouusTZFv4Gv6lX7N6fEiDEmCEUkbfzQGJTnLz59/Xu8inDfXAFwHunGECnxQ/vZgicm5XvWLAnA
	+IStVtSHAv4QafS86+tfvr14xuRQwacDQ2iNZILABimhYHQuqGB212/daeyuLBZGZy94F3sTBDYM
	xdrAJBV/B92Odms7m/cqqz+8Xtm8/f61777yeQD13h8iHlUamQCsx8qgY9gD8RJA1emuTadns6kQ
	rxowyABUvbEB+/WaujhpkipJ215VcSG3J0dyNGJnHOrb6mtN113rRH5nz3W/osZq3G5odevmOzNP
	zF5oVIx29lvbG3du3NrbvP3e9r13r67d/P67lY1b16tbi6vdVj06Mr0/4GXoUMjpqSwv82j3w2W1
	xefHn3jmmeFi8Zx3rjPoAiGqaoIgVd3avH73+rX/dWBPBdB8KhyfyuZ+quXilbZ3y53YbbTjeM/5
	JBKLGFH1OnP+xy5Nn/vICxt3r17d27i12NhdrQ1clIgRY4167/oh5LFeJXnM0rvZduKNaDHG2MRB
	9L4MSrGOghR5yLXso6LgxBgjj7BZmljOoAX351Tue81xPhBjjIgxqPr7gB7/dfX/L/9Py/8Bsk9P
	/55ysxEAAAAASUVORK5CYII=" x="24.920761" y="148.42979"/>
</g>`;

// src/main.ts
var CALIBRE_CONTAINER_FILE_NAME = "@CALIBRE.Container";
var CALIBRE_CONTAINER_FILE_PATH = `${CALIBRE_CONTAINER_FILE_NAME}.md`;
var CalibrePlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      try {
        yield this.loadSettings();
        this.addSettingTab(new CalibreSettingTab(this.app, this));
        (0, import_obsidian2.addIcon)(CALIBRE_ICON_ID, CALIBRE_ICON_SVG);
        this.addRibbonIcon(CALIBRE_ICON_ID, "Calibre", (event) => __async(this, null, function* () {
          const calibre = yield this.createOrGetCalibreContainerFile();
          if (calibre != null) {
            this.app.workspace.getLeaf(true).setViewState({
              type: "markdown",
              state: { file: calibre.path, mode: "preview" }
            });
          }
        }));
        this.app.workspace.onLayoutReady(() => {
          this.autoStylePreviewCalibreContainer(true);
        });
        this.registerEvent(this.app.workspace.on("resize", () => {
          this.autoStylePreviewCalibreContainer();
        }));
        this.registerEvent(this.app.workspace.on("layout-change", () => {
          this.autoStylePreviewCalibreContainer();
        }));
        this.registerEvent(this.app.workspace.on(`calibre:${CONTAINER_HEIGHT_CHANGED}`, () => {
          this.autoStylePreviewCalibreContainer();
        }));
        this.registerEvent(this.app.vault.on(`calibre:${SERVER_ADDRESS_CHANGED}`, () => {
          this.changeServerAddress();
        }));
      } catch (error) {
        console.log(`Load error. ${error}`);
      }
    });
  }
  autoStylePreviewCalibreContainer(autoPreview) {
    const upperCasePath = CALIBRE_CONTAINER_FILE_PATH.toUpperCase();
    this.app.workspace.getLeavesOfType("markdown").filter((leaf) => {
      var _a;
      return ((_a = leaf.getViewState().state) == null ? void 0 : _a.file).toUpperCase() == upperCasePath;
    }).forEach((leaf) => {
      if (autoPreview) {
        const state = leaf.getViewState();
        state.state.mode = "preview";
        leaf.setViewState(state);
      }
      let height = this.settings.containerHeight;
      if (this.settings.autoContainerHeight) {
        const style = getComputedStyle(leaf.view.containerEl.querySelector("div.markdown-preview-view"));
        height = (parseFloat(style.height) - parseFloat(style.paddingTop) - parseFloat(style.paddingBottom)).toString() + "px";
      }
      leaf.view.containerEl.querySelectorAll("div.calibre-container").forEach((div) => div.style.paddingTop = height);
    });
  }
  createOrGetCalibreContainerFile() {
    return __async(this, null, function* () {
      if (yield this.app.vault.adapter.exists(CALIBRE_CONTAINER_FILE_PATH, false)) {
        return this.app.vault.getRoot().children.filter((file) => file instanceof import_obsidian2.TFile).filter((file) => file.name.toUpperCase() == CALIBRE_CONTAINER_FILE_PATH.toUpperCase()).first();
      }
      return this.app.vault.create(CALIBRE_CONTAINER_FILE_PATH, calibreContainer(this.settings.address));
    });
  }
  changeServerAddress() {
    return __async(this, null, function* () {
      const calibre = yield this.createOrGetCalibreContainerFile();
      const content = yield this.app.vault.read(calibre);
      if (content.contains(CALIBRE_CONTAINER_FILE_IDENTIFIER)) {
        yield this.app.vault.modify(calibre, calibreContainer(this.settings.address));
      } else {
        console.error("INVALID CALIBRE CONTAINER FILE FOUND.");
      }
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign(DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings(type) {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
      switch (type) {
        case SERVER_ADDRESS_CHANGED:
          this.app.vault.trigger(`calibre:${type}`);
          break;
        case CONTAINER_HEIGHT_CHANGED:
          this.app.workspace.trigger(`calibre:${type}`);
          break;
        default:
          break;
      }
    });
  }
};
